/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_fks143_glvsvk_opengles_mGLLib */

#ifndef _Included_com_example_fks143_glvsvk_opengles_mGLLib
#define _Included_com_example_fks143_glvsvk_opengles_mGLLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_fks143_glvsvk_opengles_mGLLib
 * Method:    resize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_fks143_glvsvk_opengles_mGLLib_resize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_fks143_glvsvk_opengles_mGLLib
 * Method:    step
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_fks143_glvsvk_opengles_mGLLib_step
  (JNIEnv *, jclass);

/*
 * Class:     com_example_fks143_glvsvk_opengles_mGLLib
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_fks143_glvsvk_opengles_mGLLib_init
  (JNIEnv *, jclass);

/*
 * Class:     com_example_fks143_glvsvk_opengles_mGLLib
 * Method:    kill
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_fks143_glvsvk_opengles_mGLLib_kill
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
